### ISSUE TITLE
Not working with Common js Module

### ISSUE THREAD

**Issue by chertik77** [meanie/mongoose-to-json#14]
const mongoose_to_json_1 = require("@reis/mongoose-to-json");
                           ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/chertik/New Era/DrinkMaster-backend/node_modules/@reis/mongoose-to-json/index.js from /Users/chertik/New Era/DrinkMaster-backend/dist/src/schemas/category.schema.js not supported.
Instead change the require of index.js in /Users/chertik/New Era/DrinkMaster-backend/dist/src/schemas/category.schema.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/chertik/New Era/DrinkMaster-backend/dist/src/schemas/category.schema.js:14:28)

**Comment by adamreisnz** [comment]
This is expected... Please use an older version if you need common js support.

**Comment by chertik77** [comment]
Which one? You have only 3.0.0, have u?

**Comment by adamreisnz** [comment]
It was changed to a module in this commit https://github.com/adamreisnz/mongoose-to-json/commit/f9a0e70bdb31a337407066f56fabf73e13c6240e, when the version was bumped from 2.6.0 to 3.0.0.

So using version 2.6.0 is your best bet.

**Comment by chertik77** [comment]
sorry, i didn't get you. 
![Screenshot 2024-04-29 at 12 02 53](https://github.com/adamreisnz/mongoose-to-json/assets/129002577/b05314e6-ef8a-4ed8-9cfc-fed37eb74194)

**Comment by chertik77** [comment]
and when i'm using your another package **`@meanie/mongoose-to-json`** with correct version, i'm getting this error:

First param to `schema.plugin()` must be a function, got "undefined"

**Comment by chertik77** [comment]
@adamreisnz

**Comment by adamreisnz** [comment]
Sorry, I don't really support the older/commonJS version anymore. Best to use the latest, and upgrade your codebase to use modules.

**Comment by chertik77** [comment]
I use next js project, so i really cannot change structure of it, but plugin doesnt support nest js startup projects

**Comment by adamreisnz** [comment]
I suggest you just copy the source code of the project and adapt it to your
needs, or create a fork.
