### ISSUE TITLE
support for mongoose 5

### ISSUE THREAD

**Issue by isaackwan** [meanie/mongoose-to-json#4]
Currently, mongoose 5 users will see the following warning when installing: `npm WARN meanie-mongoose-to-json@1.3.0 requires a peer of mongoose@^4.5.4 but none is installed. You must install peer dependencies yourself.`

I am on mongoose 5 myself and everything seem to work. Unfortunately there is no tests in this project so I can't say that for sure, but if you got time, I figured it'd be great to pump that supported version a bit.

Cheers

**Comment by isaackwan** [comment]
Apparently I am on an old version and thus seeing that error. Sorry!

**Comment by isaackwan** [comment]
OK, I am reopening this because apparently only v1 is available on NPM, while there is a v2.2 available on GitHub (this repo). Any plans to publish v2 to NPM?

**Comment by adamreisnz** [comment]
2.2.0 is available on npm: https://www.npmjs.com/package/@meanie/mongoose-to-json

We moved to the @meanie namespace a while ago, there should have been a deprecation warning about that showing up when you install.
