### ISSUE TITLE
model.aggregate, no work

### ISSUE THREAD

**Issue by januwA** [meanie/mongoose-to-json#9]
Hi, I found this plugin at [here](https://stackoverflow.com/questions/7034848/mongodb-output-id-instead-of-id#answer-40669358) and it was in `model.find()` works fine, but when I use `model.aggregate()`, the job fails. Is there any solution?

## Using plugins
```ts
import { Schema, Types } from 'mongoose';
import * as toJSON from '@meanie/mongoose-to-json';

const EssaySchema = new Schema({
  title: String,
  content: String,
  published: { type: Date, default: Date.now },
  types: [Types.ObjectId],
  isDelete: { type: Boolean, default: false },
});

EssaySchema.plugin(toJSON);
export { EssaySchema };
```

When I use `this.essayModel.aggregate().match({ _id }).lookup({
    from: 'types',
    localField: 'types',
    foreignField: '_id',
    as: 'ts',
  })`

## expected results
```
[
  {
    "id": "5d56b4a70e593e119476a2b8",
    "types": [
      "5d56b4350e593e119476a2b4"
    ],
    "isDelete": false,
    "title": "js学习笔记",
    "content": "asdasdasdasdasdasda",
    "published": "2019-08-16T13:50:31.307Z",
    "ts": [
      {
        "id": "5d56b4350e593e119476a2b4",
        "description": "",
        "title": "js"
      }
    ]
  }
]
```

## actual results
```
[
  {
    "_id": "5d56b4a70e593e119476a2b8",
    "types": [
      "5d56b4350e593e119476a2b4"
    ],
    "isDelete": false,
    "title": "js学习笔记",
    "content": "asdasdasdasdasdasda",
    "published": "2019-08-16T13:50:31.307Z",
    "__v": 0,
    "ts": [
      {
        "_id": "5d56b4350e593e119476a2b4",
        "description": "",
        "title": "js",
        "__v": 0
      }
    ]
  }
]
```

**Comment by adamreisnz** [comment]
Aggregate framework doesn't return models, so if you want to use the plugin, you have to convert the aggregate results to models first.

Something like:

```js
const Transaction = mongoose.model('Transaction');
const result = await Transaction.aggregate([...]);
const transactions = result.transactions.map(data => new Transaction(data));
```

**Comment by januwA** [comment]
> 聚合框架不返回模型，因此如果要使用插件，则必须首先将聚合结果转换为模型。
> 
> 就像是：
> 
> ```js
> const  Transaction  =  mongoose。model（' Transaction '）;
> const  result  =  等待 事务。总计（[ ... ]）;
> const  transactions  =  结果。交易。map（data  =>  new  Transaction（data））;
> ```

Thank you for your prompt reply and solved my problem. ❤️
